version: '3'
services:
  springboot-docker-compose-app-container:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    logging:
      driver: json-file
      options:
        max-size: "500k"
        max-file: "10"