DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGSERIAL PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE AUTHORS(ID BIGSERIAL PRIMARY KEY, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255));
CREATE TABLE BOOKS(ID BIGSERIAL PRIMARY KEY, TITLE VARCHAR(255), GENREID BIGINT, AUTHORID BIGINT, FOREIGN KEY (AUTHORID) REFERENCES AUTHORS(ID), FOREIGN KEY (GENREID) REFERENCES GENRES(ID) );
